### ISSUE TITLE
StrongWolfe wrong return value

### ISSUE THREAD

**Issue by mloubout** [JuliaNLSolvers/LineSearches.jl#151]
There is one of the cases where  `StrongWolfe` returns `ϕdϕ` instead of `ϕ` in the  following line:

https://github.com/JuliaNLSolvers/LineSearches.jl/blob/81445419c98a59374cd846c03959646ad6704351/src/strongwolfe.jl#L67

**Comment by pkofod** [comment]
Wow, good catch! You don't have a reproducible example that made you realize this, do you?

**Comment by mloubout** [comment]
I found the bug as part of an Optimization package I'm developing ([SlimOptim](https://github.com/slimgroup/SlimOptim.jl)) that was giving me negative function values with very weird scales in a test.  Here is a standalone MFE 

```
using LineSearches, LinearAlgebra, Test

A = randn(100, 100)
x0 = randn(100)
b = A*x0

# Objective function and gradient
f(x) = .5*norm(A*x - b)^2
g!(gvec, x) = (gvec .= A'*(A*x-b))
fg!(gvec, x) = (g!(gvec, x); return f(x))

# Init
x = 1f1*randn(100)
gv = similar(x)

# Line search
α0 = 1f-3
ϕ0 = fg!(gv, x)
s = -1*gv
dϕ0 = dot(gv, s)
println(ϕ0, ", ", dϕ0)

# Univariate line search functions
ϕ(α) = f(x .+ α.*s)
function dϕ(α)
    g!(gv, x .+ α.*s)
    return dot(gv, s)
end
function ϕdϕ(α)
    phi = fg!(gv, x .+ α.*s)
    dphi = dot(gv, s)
    return (phi, dphi)
end

res = (StrongWolfe())(ϕ, dϕ, ϕdϕ, α0, ϕ0, dϕ0)
@test res[2] > 0
@test res[2] == ϕ(res[1])
```

**Comment by pkofod** [comment]
Okay. Thanks! 

I have projected newton in the new code for Optim and I want to include projected (L)BFGS as well. I also have spectral gradient methods, but I don't have a projected version yet. I'm saying this because there will be overlapping functionality with your package. That's of course 100% fine because I understand that sometimes you just want full control such that your own use-cases are accommodated. I'm mentioning it because I am also very happy to collaborate if you would want to at some point.

**Comment by pkofod** [comment]
Thanks a lot, and for the test as well!

**Comment by mloubout** [comment]
Thanks for the quick fix. Will there be a new release soon as well? I can work off master for now but releases make it easier for CI.

**Comment by pkofod** [comment]
Sorry,, I thought I had already tagged a patch release. I'll do it now.
