### ISSUE TITLE
Missing tolerance in `isapprox`

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/LineSearches.jl#88]
https://github.com/JuliaNLSolvers/LineSearches.jl/blob/27dd9b674eb9742490529aba5e9988a01f109ace/src/morethuente.jl#L281

The above line should have an absolute tolerance in light of https://discourse.julialang.org/t/approximate-equality/8952/4.

**Comment by anriseth** [comment]
Yeah, that makes sense. Ideally we'd set this tolerance as a parameter in
the MoreThuente type/function call, so that users can adapt it to their
optimization tolerance (for example). If you wish to make a PR that
hardcodes the tolerance, feel free to do so :)

I'd put the default to either eps(T) or, if possible, something emulating
the default tolerances we currently have in Optim.
